### ISSUE TITLE
Add support for multiple languages

### ISSUE THREAD

**Issue by sherbold** [smartshark/mecoSHARK#3]
Currently, the mecoSHARK only collects metric data for the majority language. Collecting data for multiple languages could allow a better coverage of complex projects that use multiple languages.

**Comment by ftrautsch** [comment]
Added support, set a threshold to 10%. Hence, a language processor is executed if at least 10% of all files are files supported by this processor. E.g., the c processor is executed if at least 10% c files are in the repository.
This way, we filter out scripts that are just used to, e.g., publish the documentation on github.
